version: "3.8"

services:
  config:
    container_name: amadeus_config
    image: "selcukdurukan/config-server:v.0.0.1"
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8888:8888"
    networks:
      - amadeus

  postgresql:
    container_name: amadeus_airport_postgresql
    image: postgres
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=AirportsDB
    networks:
      - amadeus

  mongodb:
    container_name: amadeus_flight_mongo
    image: mongo
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=FlightDB
    networks:
      - amadeus

  mysql:
    image: mysql:latest
    container_name: amadeus_auths_mysql
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AuthsDB
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    networks:
      - amadeus

  auth:
    container_name: amadeus_auth
    image: "selcukdurukan/auths-service:v.0.0.1"
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    ports:
      - "8080:8080"
    networks:
      - amadeus
    depends_on:
      - config
      - mysql

  airport:
    container_name: amadeus_airport
    image: "selcukdurukan/airports-service:v.0.0.1"
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    ports:
      - "8081:8081"
    networks:
      - amadeus
    depends_on:
      - config
      - postgresql

  flight:
    container_name: amadeus_flight
    image: "selcukdurukan/flights-service:v.0.0.1"
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    ports:
      - "8082:8082"
    networks:
      - amadeus
    depends_on:
      - config
      - mongodb
      - airport

volumes:
  data: {}
  mysql-data:

networks:
  amadeus:
    driver: "bridge"