server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/selcukdurukan/Amadeus-Cloud-Config-Yaml"
          default-label: main
          skip-ssl-validation: true
          username: selcukdurukan@outlook.com.tr
          password: 
      enabled: true
      uri: https://github.com/selcukdurukan/Amadeus-Cloud-Config-Yaml
      label: main
