#spring:
#  cloud:
#    config:
#      uri: http://config:8888
#  config:
#    import: "configserver:"
#  application:
#    name: airport-service-application-dev


spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"
  application:
    name: airport-service-application-dev